#pragma once

#define TAPPING_TERM 200

#define PERMISSIVE_HOLD
#define IGNORE_MOD_TAP_INTERRUPT
// #define TAPPING_FORCE_HOLD

#define TAPPING_TOGGLE  2


#define LEADER_TIMEOUT 800
#define LEADER_PER_KEY_TIMING

